apiVersion: apps/v1
kind: Deployment
metadata:
  name: pandablog
  namespace: panda
  labels:
    app: pandablog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pandablog
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: pandablog
    spec:
      containers:
        - name: pandablog
          image: panda8555/pandablog:latest
          ports:
            - containerPort: 3000 
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
